force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Participant__c/Group_Participant__c.object-meta.xml
<CustomObject>
    <label>Group Participant</label>
    <nameField>
        <displayFormat>GP-{00000}</displayFormat>
        <label>Group Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Participant__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Group Participants</relationshipLabel>
    <relationshipName>Group_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Groups Participated In</relationshipLabel>
    <relationshipName>Group_Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <formula>Group__r.Session__r.Name</formula>
    <label>Session</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Associate Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Senior Consultant</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Senior Principal</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Senior Director</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unique_Pair__c/Unique_Pair__c.object-meta.xml
<CustomObject>
    <label>Unique Pair</label>
    <nameField>
        <displayFormat>UP-{00000}</displayFormat>
        <label>Unique Pair Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unique Pairs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unique_Pair__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>Participant_1__r.Active__c &amp;&amp; Participant_2__r.Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unique_Pair__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unique_Pair__c/fields/Participant_1__c.field-meta.xml
<CustomField>
    <fullName>Participant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Participant 1</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Unique Pairs (Participant 1)</relationshipLabel>
    <relationshipName>Unique_Pairs_1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unique_Pair__c/fields/Participant_2__c.field-meta.xml
<CustomField>
    <fullName>Participant_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Participant 2</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Unique Pairs (Participant 2)</relationshipLabel>
    <relationshipName>Unique_Pairs_2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ParticipantServices.cls
public without sharing class ParticipantServices {

    public static final String SUCCESS_DO_CREATE_MESSAGE = 'Successfully updated Channel Involvement Deal Registration status.';

    
    public static void createUniquePairs(List<Participant__c> newParticipants) {
        //non-bulkified method for simplicity
        List<Unique_Pair__c> pairs = new List<Unique_Pair__c>();
        Participant__c newParticipant = newParticipants[0];
        List<Participant__c> participants = [SELECT Id, Active__c FROM Participant__c WHERE Id != :newParticipant.Id];

        for (Participant__c eachParticipant : participants) {
            // Boolean activeStatus =  newParticipant.Active__c && eachParticipant.Active__c ? true : false;
            pairs.add(new Unique_Pair__c(Participant_1__c = newParticipant.Id, Participant_2__c = eachParticipant.Id));
        }

        insert pairs;
    }

    @AuraEnabled
    public static string getExistingGroupsWithParticipants(String sessionId){
        try {
            String groups = JSON.serializePretty([
                SELECT Id, Name, (SELECT Id, Participant__r.Name, Participant__c FROM Group_Participants__r)
                FROM Group__c
                WHERE Session__c = :sessionId
                ORDER BY Name ASC
            ]);
            System.debug('groups:: ' + groups);
            return groups;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<SObject> doQuery(String soql){
        try {
            return Database.query(soql);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string getAllUniquePairs(){
        try {
            return JSON.serialize([SELECT Id, Participant_1__c, Participant_2__c, Participant_1__r.Name, Participant_2__r.Name, Active__c, Count__c FROM Unique_Pair__c WHERE Active__c = true ORDER BY Count__c ASC]);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static string getNumberOfActiveParticipants(){
        try {
            return JSON.serialize([SELECT Id, Name, Active__c, Title__c FROM Participant__c WHERE Active__c = true]);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static String createRecords(String recordsToCreate, String sessionId) {
        try {
            System.debug('recordsToCreate:: ' + recordsToCreate);
            List<GroupWrapper> records = (List<GroupWrapper>)JSON.deserialize(recordsToCreate, List<GroupWrapper>.class);
            List<Group__c> groupsToCreate = new List<Group__c>();
            for (GroupWrapper wrapper : records) {
                groupsToCreate.add(new Group__c(Name=wrapper.id, Session__c = sessionId));
            }

            insert groupsToCreate;

            Map<String,String> groupMap = new Map<String,String>();
            for (Group__c groupRecord : groupsToCreate) {
                groupMap.put(groupRecord.Name, groupRecord.Id);
            }
            
            List<Group_Participant__c> groupParticipantsToCreate = new List<Group_Participant__c>();
            for(GroupWrapper groupWrapper : records) {
                for (String participantId : groupWrapper.ids) {
                    groupParticipantsToCreate.add(new Group_Participant__c(
                        Group__c = groupMap.get(groupWrapper.id),
                        Participant__c = participantId
                    ));
                }
            }

            insert groupParticipantsToCreate;
            
            return SUCCESS_DO_CREATE_MESSAGE;
        } catch (Exception ex) {
            throw new AuraHandledException('There was an error processing your request: ' + ex.getMessage() + '. Stack Trace: ' + ex.getStackTraceString()); 
        }
    }

    @AuraEnabled
    public static String doUpdate(String recordsToUpdate) {
        try {
            List<SObject> records = (List<sObject>)JSON.deserialize(recordsToUpdate, List<SObject>.class);
            Database.update(records);
            return 'SUCCESS';
        } catch (Exception ex) {
            throw new AuraHandledException('There was an error processing your request: ' + ex.getMessage() + '. Stack Trace: ' + ex.getStackTraceString()); 
        }
    }

    public class GroupWrapper {
        String id;
        String recordId;
        List<String> ids;
    }
}